### ISSUE TITLE
JavaScript errors while loading index.html

### ISSUE THREAD

**Issue by aakarshsingh** [hieven/terraform-visual#51]
Hello -

I was able to use the CLI to generate the HTML visual report using my plan.json

When I try to view the generated HTML, I get JavaScript errors and the UI says: 

`An unexpected error has occurred.`

Looking at the console, there are two errors. 

1. Error in framework.d557686129d5a5cc0c94.js
2. Error in main-00c80b622f2ad2cfc5b5.js

Both errors are the same:
`
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at a (71247caf95475e3ea7f9a0f8a30beb258b23d005.8b7e937f17f885a06544.js:1:3494)
    at Object.fromTerraformPlanResourceChange (71247caf95475e3ea7f9a0f8a30beb258b23d005.8b7e937f17f885a06544.js:1:4708)
    at Object.fromTerraformPlanResourceChange (71247caf95475e3ea7f9a0f8a30beb258b23d005.8b7e937f17f885a06544.js:1:4548)
    at 71247caf95475e3ea7f9a0f8a30beb258b23d005.8b7e937f17f885a06544.js:1:14485
    at uo (framework.d557686129d5a5cc0c94.js:1:94944)
    at Nu (framework.d557686129d5a5cc0c94.js:1:114188)
    at t.unstable_runWithPriority (framework.d557686129d5a5cc0c94.js:1:3950)
    at $l (framework.d557686129d5a5cc0c94.js:1:56504)
    at Pu (framework.d557686129d5a5cc0c94.js:1:113939)
    at du (framework.d557686129d5a5cc0c94.js:1:105436)
`

Am I doing something wrong?

**Comment by aakarshsingh** [comment]
Seems like it is not happy with the fact that I ran some of it on windows. Running end to end on Ubuntu gave no errors.

**Comment by lpic10** [comment]
still, any reason for it to not be supported on windows?
